export const reasons = [
  "You always know how to make me smile even on difficult days.",
  "Your laugh is my favorite sound in the whole world.",
  "The way your eyes light up when you see something cute.",
  "You are incredibly kind and compassionate to everyone.",
  "Your warm hugs that make me feel entirely safe.",
  "You're completely gorgeous inside and out.",
  "The adorable way you talk about the things you are passionate about.",
  "Your endless patience with me.",
  "You encourage me to be the very best version of myself.",
  "You understand me like nobody else does.",
  "You make the most boring moments feel like an adventure.",
  "The way you look at me makes me feel so loved.",
  "You are my best friend and my soulmate.",
  "Your impeccable taste in all things cute, like plushies and handmade stuff.",
  "You always support my dreams, no matter how crazy they are.",
  "Your silly jokes that somehow always make me laugh.",
  "The way you scrunch your nose when you're thinking.",
  "You are so smart and brilliant.",
  "Because you love sunflowers and lilies, and you are as bright and beautiful as them.",
  "You remember the little details about me.",
  "You always smell so incredibly good.",
  "The way your hand perfectly fits in mine.",
  "You are my safe space.",
  "The sweet little messages you send me randomly.",
  "Because even your flaws are perfect to me.",
  "You challenge me to grow and learn every day.",
  "Your taste in music is amazing.",
  "The cute little sounds you make when you are happy.",
  "You are fiercely loyal to the people you love.",
  "The way you deeply care about animals.",
  "You make everyday life feel a little bit more magical.",
  "Your heart is so pure and beautiful.",
  "Because you always know when I need a hug.",
  "You have the cutest smile I have ever seen.",
  "You accept me exactly as I am.",
  "Your voice is incredibly soothing to me.",
  "You still give me butterflies after all this time.",
  "The way you fall asleep on my shoulder.",
  "Because your happiness truly is my happiness.",
  "You are the most thoughtful person I know.",
  "You inspire me with your resilience.",
  "The way we can communicate without even using words.",
  "You are my favorite person to do completely nothing with.",
  "You always have the best advice when I am lost.",
  "Your incredible creativity and imagination.",
  "Because of the way you say my name.",
  "You make me feel invincible.",
  "You are always so beautifully authentic and genuine.",
  "The way you get excited over the smallest things.",
  "You love me even when I am difficult to love.",
  "Because I can completely be myself around you.",
  "Your beautiful, radiant soul.",
  "Every single message from you brightens my day.",
  "You make all my fears disappear.",
  "The way you cuddle up to me when it's cold.",
  "Because loving you is the easiest thing I have ever done.",
  "Your boundless empathy for others.",
  "The way you always believe in me, even when I don't.",
  "Because you are my absolute dream come true.",
  "You make the world a much better place just by being in it.",
  "The sweet ways you show you care.",
  "You have an absolutely beautiful mind.",
  "Because you brought so much light into my life.",
  "You make every memory we share completely unforgettable.",
  "The way you look in my favorite shirt.",
  "You are the reason I wake up happy every morning.",
  "Your cute little habits that I adore.",
  "Because of how deeply you love.",
  "You make me feel like the luckiest person alive.",
  "The way you can turn any bad day completely around.",
  "Because your hugs feel completely like magic.",
  "You are the most precious thing in my entire life.",
  "Because you make me excited for the future.",
  "Your incredible strength and courage.",
  "The way you look deeply into my eyes.",
  "Because simply holding your hand feels like absolute home.",
  "You are my greatest adventure.",
  "Because our souls just perfectly understand each other.",
  "You always manage to surprise me.",
  "The incredible gentleness of your touch.",
  "Because you are the peanut butter to my jelly.",
  "You make me want to be romantic.",
  "Your beautiful, genuine laugh that fills up the room.",
  "Because you are the missing piece I never knew I was looking for.",
  "You always listen to me.",
  "The way you completely light up any room you walk into.",
  "Because you make my heart skip a beat.",
  "Your incredible sweetness.",
  "Because you always make time for us.",
  "The way you completely melt my heart every single day.",
  "Because I simply cannot imagine my life without you.",
  "You are my absolute greatest blessing.",
  "Because of the way we completely belong together.",
  "You are the most beautiful person I have ever known.",
  "Because you are completely, undeniably, entirely 'the one'.",
  "The way you make every single song feel like it's about us.",
  "Because I honestly fall more in love with you every single day.",
  "You are my absolute whole entire world.",
  "Because forever still doesn't seem long enough with you.",
  "Because you are Sreeparna, and there is no one else quite like you."
];
